/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedPagesRouteImport } from './routes/_ProtectedPages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedPagesQuacksRouteImport } from './routes/_ProtectedPages/quacks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPagesRoute = ProtectedPagesRouteImport.update({
  id: '/_ProtectedPages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPagesQuacksRoute = ProtectedPagesQuacksRouteImport.update({
  id: '/quacks',
  path: '/quacks',
  getParentRoute: () => ProtectedPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/quacks': typeof ProtectedPagesQuacksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/quacks': typeof ProtectedPagesQuacksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_ProtectedPages': typeof ProtectedPagesRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_ProtectedPages/quacks': typeof ProtectedPagesQuacksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/quacks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/quacks'
  id:
    | '__root__'
    | '/'
    | '/_ProtectedPages'
    | '/login'
    | '/signup'
    | '/_ProtectedPages/quacks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedPagesRoute: typeof ProtectedPagesRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ProtectedPages': {
      id: '/_ProtectedPages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ProtectedPages/quacks': {
      id: '/_ProtectedPages/quacks'
      path: '/quacks'
      fullPath: '/quacks'
      preLoaderRoute: typeof ProtectedPagesQuacksRouteImport
      parentRoute: typeof ProtectedPagesRoute
    }
  }
}

interface ProtectedPagesRouteChildren {
  ProtectedPagesQuacksRoute: typeof ProtectedPagesQuacksRoute
}

const ProtectedPagesRouteChildren: ProtectedPagesRouteChildren = {
  ProtectedPagesQuacksRoute: ProtectedPagesQuacksRoute,
}

const ProtectedPagesRouteWithChildren = ProtectedPagesRoute._addFileChildren(
  ProtectedPagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedPagesRoute: ProtectedPagesRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
